---
title: "text-mining-group-work"
author: "Vladyslav Gorbunov, Larissa Pagliarin"
date: "`r Sys.Date()`"
output:
  prettydoc::html_pretty:
    theme: "hpstr" 
  html_document:
    toc: true
    toc_float: true
---

## Data Import and Preparation

We Import the dataset *SP500_data.csv* and make a copy to work with it and named it *data*. We copy it so we can be secure that i do not make any changes in the original dataset.
<br>
We use several libraries to process the tasks and get the output that is asked.


```{r library, include=FALSE}
# Load packages and libraries, if not already available.
libraries = c("readxl", "ggplot2", "knitr", "dplyr")

lapply(libraries, function(x) if (!(x %in% installed.packages())) {
  install.packages(x)
})

lapply(libraries, library, quietly = TRUE, character.only = TRUE)
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r data, include=FALSE}
# Load data set and make a copy of the original
SP500_data <- read.csv("SP500_data.csv")
data <- SP500_data
```

<br>
















